---
when:
  - event: push
    branch: main

steps:
  - name: Install dependencies
    image: paulhuggett/ubuntu-build
    commands:
      - sudo apt-get update
      - sudo apt-get install -y build-essential device-tree-compiler gcc-10

  - name: Build
    image: paulhuggett/ubuntu-build
    commands:
      - "rm -rf ./build"
      - mkdir build
      - cd ./build
      - mkdir ./install
      - CXXFLAGS="-Wnon-virtual-dtor"
      - CFLAGS="-Werror -Wignored-qualifiers -Wunused-function -Wunused-parameter -Wunused-variable"
      - "../configure --prefix=$(pwd)/install"
      - make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)"
      - make check
      - make install install-hdrs-list.h
      # check that help message prints without error
      - ./install/bin/spike -h

  - name: Tar files
    image: paulhuggett/ubuntu-build
    commands:
      - cd ./build
      - rm -r install/include install/lib
      - tar -cvJf spike.tar.xz --transform s/install/spike/ install

  - name: Upload Artifact
    image: paulhuggett/ktransfer:latest
    pull: true
    settings:
      drive_id: 641975
      token:
        from_secret: API_TOKEN
      method: put
      name: spike.tar.xz
...
